In [1]:
import pandas as pd
import dask.dataframe as dd
import json

# Advanced removal
Similarities were found with tf-idf representation and cosine similarity. Since thus approach is time and memory consuming, it was performed externally and resluts are imported here.  
Warning: dask index is not very reliable, so it is better to drop dupplicates by index with pandas

In [2]:
max_sim = 0.92

sim = pd.read_csv('sim-h-80.csv')
sim = sim.loc[sim.similarity > max_sim]
grouped = sim.groupby(['I1'])['I2'].apply(list).reset_index(name='duplicates')
ids_to_be_removed = set()
for l in list(grouped.duplicates):
    ids_to_be_removed.update(l)

In [3]:
dataset_pd = pd.read_csv('0-datasets/v-1.0.0-beta-h/dataset-0.csv')
dataset_pd = dataset_pd.drop(list(ids_to_be_removed))
dataset_pd.describe()

,title,ingredients,directions,link,source
count,2234224,2234224,2234224,2234224,2234224
unique,1315799,2229334,2214696,2234224,2
top,Chicken Casserole,"[""1 paper, serviette (large)"", ""1 cloth, servi...","[""Mix all ingredients together.""]",www.cookbooks.com/Recipe-Details.aspx?id=36362,Gathered
freq,4099,58,274,1,1645982

# Finally remove this kind of useless recipes
Removing manually some interesting recipes found during exploratory analysis

In [4]:
serviette = dataset_pd.loc[dataset_pd.ingredients.map(lambda x: x.find("1 paper, serviette")>0)]

In [5]:
serviette.head()

,title,ingredients,directions,link,source
1208466,"Serviette Napkin Folding , Basic With Napkin Ring","[""1 paper, serviette (large)"", ""1 cloth, servi...","[""Lay your serviette square out flat before yo...",www.food.com/recipe/serviette-napkin-folding-b...,Gathered
1718740,"Serviette/Napkin Folding, a Neck Tie for Dad...","[""1 paper, serviette (large)"", ""1 cloth, servi...","[""Lay your serviette out flat before you in a ...",www.food.com/recipe/serviette-napkin-folding-a...,Recipes1M
1718823,"Serviette/Napkin, Chic Knot","[""1 paper, serviette (large)"", ""1 cloth, servi...","[""Lay your serviette out before you in a squar...",www.food.com/recipe/serviette-napkin-chic-knot...,Recipes1M
1719384,"Serviette/Napkin Folding, Candle in a Wine Gla...","[""1 paper, serviette (large)"", ""1 cloth, servi...","[""Lay your serviette out flat before you in a ...",www.food.com/recipe/serviette-napkin-folding-c...,Recipes1M
1730385,"Serviette/Napkin Folding, Easy Heart ( Suits P...","[""1 paper, serviette (large)"", ""1 cloth, servi...","[""Lay your serviette square out flat before yo...",www.food.com/recipe/serviette-napkin-folding-e...,Recipes1M

In [6]:
serviette.describe()

,title,ingredients,directions,link,source
count,66,66,66,66,66
unique,66,7,66,66,2
top,"Serviette/Napkin Folding, Orchid","[""1 paper, serviette (large)"", ""1 cloth, servi...","[""Place your serviette flat before you in a sq...",www.food.com/recipe/serviette-napkin-folding-c...,Recipes1M
freq,1,58,1,1,65

In [7]:
nice = dataset_pd.loc[dataset_pd.ingredients.map(lambda x: x.find("heartful of love")>0)]

In [8]:
nice.head()

,title,ingredients,directions,link,source
323,Recipe For Happiness,"[""2 heaping c. patience"", ""1 heartful of love""...","[""Sprinkle generously with kindness."", ""Add pl...",www.cookbooks.com/Recipe-Details.aspx?id=577815,Gathered
1030,Lifetime Recipe,"[""2 heaping c. of patience"", ""1 heartful of lo...","[""Sprinkle generously with kindness."", ""Add pl...",www.cookbooks.com/Recipe-Details.aspx?id=244318,Gathered
87299,A Recipe For A Happy Family,"[""1 heartful of love"", ""1 portion of understan...","[""Combine ingredients and stir frequently with...",www.cookbooks.com/Recipe-Details.aspx?id=957184,Gathered
95175,Lifetime Recipe,"[""2 heaping c. patience"", ""2 handfuls generosi...","[""My favorite dish to bring to the Cast Partie...",www.cookbooks.com/Recipe-Details.aspx?id=1054052,Gathered
135600,Recipe For Happiness,"[""2 heaping c. of patience"", ""1 heartful of lo...","[""Take 2 parts of unselfishness and 1 part of ...",www.cookbooks.com/Recipe-Details.aspx?id=998388,Gathered

In [9]:
nice.describe()

,title,ingredients,directions,link,source
count,13,13,13,13,13
unique,8,13,13,13,1
top,Recipe For Happiness,"[""2 heaping c. patience"", ""1 heartful of love""...","[""Sprinkle generously with kindness."", ""Add pl...",www.cookbooks.com/Recipe-Details.aspx?id=896081,Gathered
freq,5,1,1,1,13

In [10]:
only_ingredients = dataset_pd.loc[dataset_pd.ingredients.map(lambda x: x == '["Ingredients"]')]

In [11]:
only_ingredients.head()

,title,ingredients,directions,link,source
1308562,Glühwien(Mulled Wine),"[""Ingredients""]","[""Directions"", """", ""Combine the cider, wine, h...",www.epicurious.com/recipes/member/views/gluhwi...,Gathered
1309817,Slow Cooker Vegetable Curry,"[""Ingredients""]","[""Directions"", """", ""1. In a 3-1/2- to 5-quart ...",www.epicurious.com/recipes/member/views/slow-c...,Gathered
1315626,Coconut Cream Pie,"[""Ingredients""]","[""1. In a small saucepan, combine the sugar, c...",www.epicurious.com/recipes/member/views/coconu...,Gathered
1317802,Pumpkin Risotto,"[""Ingredients""]","[""Directions"", """", ""In a medium-size heavy sau...",www.epicurious.com/recipes/member/views/pumpki...,Gathered
1327387,Rosemary Skewers,"[""Ingredients""]","[""Strip all but 1 to 2 inches of rosemary leav...",www.epicurious.com/recipes/member/views/rosema...,Gathered

In [12]:
dataset_pd.iloc[1308487].directions

'["1. Once all of the vegetable are chopped, combine ingredients in a large bowl and mix well. Taste for vinegar. The gazpacho should have a definite edge of vinegar without tasting sour.", "", "Yields 4 quarts Serves 8-10", "", "A quick lesson in cutting small cubes with photo below:", "", "1. Cut whatever vegetable you are using into long, uniform stripes. If it\'s peppers and you are really compulsive you can trim the ends and cube them separately, but that level of compulsiveness is not recommended.", "", "", "", "2. Line up the strips and cut across into small cubes.", "", "", "", "If the cubes seem too large, you can dice them-not as perfectly cubed, but perfectly fine.", "", "Optional croutons", "1. Allow bread cubes to dry out at least overnight. The drying prevents bread from absorbing too much oil.", "2. Preheat oven to 325 degrees. Place dried cubes in bowl. Pour oil down and around edge of bowl and toss croutons to distribute oil. Transfer oiled cubes to rimmed baking sheet. Bake on middle shelf of oven for 25 to 30 minutes until golden. Allow to cool. Add 1/2 teaspoon of coarse salt and toss.", "", "", "", "Gazpacho with optional croutons and a few torn leaves for garnish.", "", "Pass croutons on the side in a bowl with a soup spoon for your guests to add to their soup."]'

In [13]:
dataset_pd = dataset_pd.loc[dataset_pd.ingredients.map(lambda x: x.find("1 paper, serviette")==-1 and x.find("heartful of love")==-1 and x != '["Ingredients"]' and x!='[]')]

In [14]:
dataset_pd.describe()

,title,ingredients,directions,link,source
count,2234093,2234093,2234093,2234093,2234093
unique,1315690,2229313,2214567,2234093,2
top,Chicken Casserole,"[""1 c. peanut butter"", ""1 c. sugar"", ""1 egg""]","[""Mix all ingredients together.""]",www.cookbooks.com/Recipe-Details.aspx?id=36362,Gathered
freq,4099,28,274,1,1645918

# Store final result

In [16]:
dataset_pd.to_csv('0-datasets/v-1.1.0-single-h.csv', index=False)